@startuml abstract1

class Shape {
    -width: int
    -height: int
    ---
    Shape()
    +draw() 
}
class Circle {
    +draw()
}
class Rectangle {
    +draw()
}

Shape <|-- Circle
Shape <|-- Rectangle

abstract class Shape2 {
    -width: int
    -height: int
    ---
    Shape()
    +abstract draw() 
}
class Circle2 extends Shape2 {
    +draw()
}
class Rectangle2 extends Shape2{
    +draw()
}

@enduml 


